version: '3'
services:
  python-soccer-data:
    container_name: soccer-beat-the-machine_python-soccer-data
    build: ./app/python-soccer-data
    image: python-soccer-data:latest
    environment:
     - DEV_MODE=1
    volumes:
      - soccer-data:/usr/app/data 

  soccer-db:
    environment:
      POSTGRES_USER: coveto-soccer
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: soccer
    image: postgres:latest
    networks:
      - soccer-network
    ports:
      - 5405:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/1-init.sql

  python-soccer-dao:
    container_name: soccer-beat-the-machine_python-soccer-dao
    build: ./app/python-soccer-dao
    image: python-soccer-dao:latest
    environment:
     - DEV_MODE=1
    depends_on:
      - soccer-db
    networks:
      - soccer-network
    volumes:
      - soccer-data:/usr/app/data

  #python-soccer-torch:
  #  build: ./app/soccer-ml-model
  #  command: tail -f /dev/null
  #  image: python-soccer-torch:latest
  #  volumes:
  #    - soccer-data:/usr/app/data

  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - python-soccer-data
      - python-soccer-dao
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/scheduler/config.ini:/etc/ofelia/config.ini

volumes: 
  soccer-data:

  postgres-data:

networks: 
  soccer-network: