version: '3'
services:
  python-soccer-data:
    build: ./src/python-soccer-data
    image: python-soccer-data:latest
    volumes:
      - soccer-data:/usr/data 

  soccer-db:
    environment:
      POSTGRES_USER: coveto-soccer
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: soccer
    image: postgres:latest
    networks:
      - soccer-network
    ports:
      - 5405:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/1-init.sql

  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - python-soccer-data
      - python-soccer-dao
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/scheduler/config.ini:/etc/ofelia/config.ini

  python-soccer-dao:
    build: ./src/python-soccer-dao
    image: python-soccer-dao:latest
    depends_on:
      - soccer-db
    networks:
      - soccer-network
    volumes:
      - soccer-data:/usr/data

volumes: 
  soccer-data:

  postgres-data:

networks: 
  soccer-network: